--liquibase formatted sql
--changeset username:2025-03-16_create_table_user labels:firstTime

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255)
    );

COMMENT ON TABLE users IS 'Таблица пользователей';
COMMENT ON COLUMN users.id IS 'Идентификатор';
COMMENT ON COLUMN users.username IS 'Имя пользователя';
COMMENT ON COLUMN users.email IS 'Электронная почта';
COMMENT ON COLUMN users.password IS 'Пароль';

--rollback DROP TABLE IF EXISTS users;