spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db_java
    username: root
    password: roottoor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
    default-schema: public

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs



logging:
  level:
    org.springframework: DEBUG
    org.springdoc: DEBUG