--liquibase formatted sql
--changeset username:2025-03-16_create_table_ads labels:ads

CREATE TABLE ads
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    price DOUBLE PRECISION,
    user_id INTEGER,
    created_at TIMESTAMP
);

COMMENT ON TABLE ads IS 'Таблица объявлений';
COMMENT ON COLUMN ads.id IS 'Идентификатор объявления';
COMMENT ON COLUMN ads.title IS 'Заголовок объявления';
COMMENT ON COLUMN ads.description IS 'Описание объявления';
COMMENT ON COLUMN ads.price IS 'Цена объявления';
COMMENT ON COLUMN ads.user_id IS 'Идентификатор пользователя, создавшего объявление';
COMMENT ON COLUMN ads.created_at IS 'Дата и время создания объявления';

--rollback DROP TABLE ads;

--changeset username:2025-03-16_add_fk_to_ads labels:ads
ALTER TABLE ads
    ADD CONSTRAINT fk_ads_user_id
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

--rollback ALTER TABLE ads DROP CONSTRAINT fk_ads_user_id;